# Generated by Django 3.2.8 on 2022-02-17 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('RatioToMetric', models.DecimalField(decimal_places=2, max_digits=100000000000)),
                ('PictureUrl', models.ImageField(upload_to='catagory/images/')),
                ('ReOrderNumber', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('FlagPicture', models.ImageField(upload_to='country/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('AreaInUnits', models.DecimalField(decimal_places=3, max_digits=100000000000)),
                ('Name', models.CharField(max_length=50)),
                ('FarmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('CompanyDescription', models.CharField(max_length=3000)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Cell', models.BigIntegerField(unique=True)),
                ('DateJoined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitsOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=30)),
                ('RatioToMetric', models.DecimalField(decimal_places=2, max_digits=100000000000)),
                ('MesurementSymbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=3000)),
                ('ProductCode', models.CharField(max_length=200)),
                ('UnitsInStock', models.IntegerField()),
                ('UnitsOnOrder', models.IntegerField()),
                ('PictureUrl', models.ImageField(upload_to='products/images/')),
                ('ReOrderNumber', models.CharField(max_length=5)),
                ('Tax', models.DecimalField(decimal_places=2, max_digits=100000000000)),
                ('TaxExclPrice', models.DecimalField(decimal_places=2, max_digits=100000000000)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.category')),
                ('MerchantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.merchants')),
                ('UnitsInStock_UnitsInStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.unitsofmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('CatagoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.category')),
                ('FarmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.farm')),
                ('FieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.field')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.products')),
                ('UnitsOfMesurmentId_Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.unitsofmeasurement')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='UnitsOfMesurmentId_Area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.unitsofmeasurement'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateToUsd', models.DecimalField(decimal_places=2, max_digits=1000000000000000)),
                ('CurrencySymbol', models.CharField(max_length=5)),
                ('CountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.country')),
            ],
        ),
    ]
