# Generated by Django 3.2.8 on 2022-02-17 23:16

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='FlagPicture',
            field=models.ImageField(null=sqlalchemy.sql.expression.true, upload_to='CountryFlag/images/'),
        ),
    ]
