# Generated by Django 3.2.8 on 2022-02-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_alter_country_flagpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='FlagPicture',
            field=models.ImageField(upload_to='CountryFlag/'),
        ),
    ]
